q_to_d = {
     'MINUS': 'MINUS', # '!' key unknown to Blender.
     'EQUAL': 'EQUAL', # '#' key unknown to Blender.
     'Q': 'SEMI_COLON',
     'W': 'COMMA',
     'E': 'PERIOD',
     'R': 'P',
     'T': 'Y',
     'Y': 'F',
     'U': 'G',
     'I': 'C',
     'O': 'R',
     'P': 'L',
     'LEFT_BRACKET': 'SLASH',
     'RIGHT_BRACKET': 'RIGHT_BRACKET', # '@' key unknown to Blender.
     'BACK_SLASH': 'BACK_SLASH',
     'A': 'A',
     'S': 'O',
     'D': 'E',
     'F': 'U',
     'G': 'I',
     'H': 'D',
     'J': 'H',
     'K': 'T',
     'L': 'N',
     'SEMI_COLON': 'S',
     'QUOTE': 'MINUS',
     'Z': 'QUOTE',
     'X': 'Q',
     'C': 'J',
     'V': 'K',
     'B': 'X',
     'N': 'B',
     'M': 'M',
     'COMMA': 'W',
     'PERIOD ': 'V',
     'SLASH': 'Z',
}

